// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOsEI6NX6tiGH2QmX33tOrPFRfiUVvtXI',
    appId: '1:291106180691:web:ede03a73a7610642a240a6',
    messagingSenderId: '291106180691',
    projectId: 'greenmind-cf606',
    authDomain: 'greenmind-cf606.firebaseapp.com',
    storageBucket: 'greenmind-cf606.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy3mDtVcr5-D4EYQ1wW2W3H0OlmH51uos',
    appId: '1:291106180691:android:28027c19f8d2d679a240a6',
    messagingSenderId: '291106180691',
    projectId: 'greenmind-cf606',
    storageBucket: 'greenmind-cf606.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOsEI6NX6tiGH2QmX33tOrPFRfiUVvtXI',
    appId: '1:291106180691:web:4b9e8badf11a9818a240a6',
    messagingSenderId: '291106180691',
    projectId: 'greenmind-cf606',
    authDomain: 'greenmind-cf606.firebaseapp.com',
    storageBucket: 'greenmind-cf606.firebasestorage.app',
  );
}
